/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Logica.CPP;
import java.util.Calendar;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import modelo.Compra;
import persistencia.DAOCompra;
import persistencia.DAOProducto;

/**
 *
 * @author dcorr
 */
public class GUICompra extends javax.swing.JFrame {

    /**
     * Creates new form GUICompra
     */
    public GUICompra() {
        initComponents();
        Calendar c1 = Calendar.getInstance();
        String dia = Integer.toString(c1.get(Calendar.DATE));
        String mes = Integer.toString(c1.get(Calendar.MONTH)+1);
        String annio = Integer.toString(c1.get(Calendar.YEAR));
        
        String fecha = dia+"/"+mes+"/"+annio;
        jTextFieldFecha.setText(fecha);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2TablaCompras = new javax.swing.JTable();
        jButtonRegresar = new javax.swing.JButton();
        jTextFieldFecha = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButtonBuscarCompra = new javax.swing.JButton();
        jTextField1CodigoCompra = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2PrecioDeCompra = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3Cantidad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField1codigoproducto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4NombreProducto = new javax.swing.JTextField();
        jButtonAñadirCompraProducto = new javax.swing.JButton();
        jButtonFinalizarCompra = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField1FechaVencimiento = new javax.swing.JTextField();
        jTextField2FechaAviso = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2TablaCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo Compra", "Nombre Producto", "Cantidad", "Precio Compra", "Fecha", "Precio neto", "codigoProducto", "Fecha Vencimiento", "Fecha Aviso"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2TablaCompras);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 268, 700, 109));

        jButtonRegresar.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jButtonRegresar.setText("Regresar");
        jButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        jTextFieldFecha.setEditable(false);
        getContentPane().add(jTextFieldFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 68, -1));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel5.setText("Fecha");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jButtonBuscarCompra.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jButtonBuscarCompra.setText("Buscar");
        getContentPane().add(jButtonBuscarCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, -1, -1));
        getContentPane().add(jTextField1CodigoCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 93, -1));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel1.setText("codigo compra");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel2.setText("Precio de compra");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));
        getContentPane().add(jTextField2PrecioDeCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 68, -1));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel3.setText("cantidad");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 60, -1));
        getContentPane().add(jTextField3Cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 66, -1));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel6.setText("codigo producto");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jTextField1codigoproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1codigoproductoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1codigoproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 68, -1));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel4.setText("nombre producto");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));
        getContentPane().add(jTextField4NombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 100, -1));

        jButtonAñadirCompraProducto.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jButtonAñadirCompraProducto.setText("Añadir");
        jButtonAñadirCompraProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAñadirCompraProductoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAñadirCompraProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, -1, -1));

        jButtonFinalizarCompra.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jButtonFinalizarCompra.setText("Finalizar compra");
        jButtonFinalizarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFinalizarCompraActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFinalizarCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/640-6400983_0-carrito-de-compras-rosado_opt.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 190, 180));

        jLabel8.setText("Fecha de vencimiento");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, -1, 20));

        jLabel10.setText("Fecha de Aviso");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, -1, -1));
        getContentPane().add(jTextField1FechaVencimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 110, -1));
        getContentPane().add(jTextField2FechaAviso, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 110, -1));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/blue-wave-background-photoshop-backgrounds_opt.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 440));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAñadirCompraProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAñadirCompraProductoActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelo=(DefaultTableModel) jTable2TablaCompras.getModel(); 
        Object [] fila=new Object[9];
        
        fila[0]=Integer.parseInt(jTextField1CodigoCompra.getText()); 

        fila[1]=jTextField4NombreProducto.getText(); 

        fila[2]=Integer.parseInt(jTextField3Cantidad.getText()); 

        fila[3]=Double.parseDouble(jTextField2PrecioDeCompra.getText()); 
        
        fila[4]=jTextFieldFecha.getText(); 
        
        fila[5]=Double.parseDouble(jTextField2PrecioDeCompra.getText())*Integer.parseInt(jTextField3Cantidad.getText());
        
        fila[6]= jTextField1codigoproducto.getText();
        
        fila[7]=jTextField1FechaVencimiento.getText();
         
        fila[8]=jTextField2FechaAviso.getText();
        
 
        

        modelo.addRow(fila); 
        
        jTable2TablaCompras.setModel(modelo);
    }//GEN-LAST:event_jButtonAñadirCompraProductoActionPerformed

    private void jButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);  
    }//GEN-LAST:event_jButtonRegresarActionPerformed

    private void jButtonFinalizarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFinalizarCompraActionPerformed
        // TODO add your handling code here:
         Compra nuevaCompra= new Compra();
         JTable jTableTablaCompras1 = jTable2TablaCompras;
            nuevaCompra.setcodigoCompra((int) jTableTablaCompras1.getValueAt(0, 0));
            nuevaCompra.setPrecioCompraProducto((double) jTableTablaCompras1.getValueAt(0, 3));
            nuevaCompra.setCantidad((int) jTableTablaCompras1.getValueAt(0, 2));
            nuevaCompra.setFecha((String) jTableTablaCompras1.getValueAt(0, 4));
            nuevaCompra.setCodigoProducto(Integer.parseInt((String) jTableTablaCompras1.getValueAt(0, 6)));
            
            DAOCompra.conexion();
            DAOCompra.GuardarCompra(nuevaCompra);
        
        
        int filas=jTableTablaCompras1.getRowCount();
        int i;
        
        for (i =0 ; i<filas;i++){
                   
                                   
            nuevaCompra.setcodigoCompra((int) jTableTablaCompras1.getValueAt(i, 0));
            nuevaCompra.setCantidad((int) jTableTablaCompras1.getValueAt(i, 2));
            nuevaCompra.setPrecioCompraProducto((double) jTableTablaCompras1.getValueAt(i, 3));
            nuevaCompra.setFecha((String) jTableTablaCompras1.getValueAt(i, 4));
            nuevaCompra.setCodigoProducto(Integer.parseInt((String) jTableTablaCompras1.getValueAt(i, 6)));
            
            String FechaVencimiento= (String) jTableTablaCompras1.getValueAt(i, 7);
            String FechaAviso= (String) jTableTablaCompras1.getValueAt(i, 8);
            double TotalVenta=(double) jTableTablaCompras1.getValueAt(i, 5);
            
            DAOCompra.conexion();
           
            DAOCompra.GuardarCompraProducto(nuevaCompra, FechaVencimiento, FechaAviso,TotalVenta);
            DAOProducto.conexion();
            int CppActual= DAOProducto.consultarCpp(nuevaCompra.getCodigoProducto());
            int CantidadStockActual=DAOProducto.consultarCantidad(nuevaCompra.getCodigoProducto());
           
            DAOProducto.ActualizarCantidad(nuevaCompra.getCodigoProducto(), nuevaCompra.getCantidad(),1);
            
          
            
            double CppNuevo;
            CppNuevo = CPP.ActualizarCpp(CantidadStockActual, CppActual, nuevaCompra.getCantidad(),nuevaCompra.getPrecioCompraProducto());
            DAOProducto.conexion();
            DAOProducto.ActualizarCpp(nuevaCompra.getCodigoProducto(), CppNuevo);
            
            
        
        }
    }//GEN-LAST:event_jButtonFinalizarCompraActionPerformed

    private void jTextField1codigoproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1codigoproductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1codigoproductoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUICompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUICompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUICompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUICompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUICompra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAñadirCompraProducto;
    private javax.swing.JButton jButtonBuscarCompra;
    private javax.swing.JButton jButtonFinalizarCompra;
    private javax.swing.JButton jButtonRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2TablaCompras;
    private javax.swing.JTextField jTextField1CodigoCompra;
    private javax.swing.JTextField jTextField1FechaVencimiento;
    private javax.swing.JTextField jTextField1codigoproducto;
    private javax.swing.JTextField jTextField2FechaAviso;
    private javax.swing.JTextField jTextField2PrecioDeCompra;
    private javax.swing.JTextField jTextField3Cantidad;
    private javax.swing.JTextField jTextField4NombreProducto;
    private javax.swing.JTextField jTextFieldFecha;
    // End of variables declaration//GEN-END:variables
}
