/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.util.ArrayList;
import persistencia.DAOInformes;


/**
 *
 * @author dcorr
 */
public class GUIInformes extends javax.swing.JFrame {

    /**
     * Creates new form GUIInformes
     */
    public GUIInformes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1FechaUno = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2FechaDos = new javax.swing.JTextField();
        jButton1Consultar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButtonConsultarStock = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1Regresar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        jLabel1.setText("Consultar Informe por categoria en un rango de tiempo ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 34, 536, -1));
        getContentPane().add(jTextField1FechaUno, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 93, 80, -1));

        jLabel2.setText("a");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 96, 24, -1));
        getContentPane().add(jTextField2FechaDos, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 93, 98, -1));

        jButton1Consultar.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jButton1Consultar.setText("Consultar");
        jButton1Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1Consultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 92, -1, -1));

        jLabel3.setFont(new java.awt.Font("Elephant", 0, 14)); // NOI18N
        jLabel3.setText("Consultar cantidad de stock de cada producto");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, -1, 31));

        jButtonConsultarStock.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jButtonConsultarStock.setText("Generar Informe");
        jButtonConsultarStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarStockActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonConsultarStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"comida", null},
                {"frutas", null}
            },
            new String [] {
                "Categoria", "Total Vendido"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 132, 375, 91));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "producto", "stock"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 306, -1, 119));

        jButton1Regresar.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jButton1Regresar.setText("regresar");
        jButton1Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1RegresarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1Regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 443, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/pngtree-vector-invoice-vector-icon-png-image_4072926_opt.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, -1, 220));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/blue-wave-background-photoshop-backgrounds_opt.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ConsultarActionPerformed
        // TODO add your handling code here:
        ArrayList<Integer> Resultadoventas = new ArrayList<>();
        
        DAOInformes.conexion();
        Resultadoventas=DAOInformes.ConsultarInformeCategorias(jTextField1FechaUno.getText(), jTextField2FechaDos.getText());
        int i;
       
        for (i=0;i<Resultadoventas.size();i++){
            
         
        jTable1.setValueAt(Resultadoventas.get(i), i ,1);
        }
        
         
    }//GEN-LAST:event_jButton1ConsultarActionPerformed

    private void jButtonConsultarStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarStockActionPerformed
        // TODO add your handling code here:
        
        ArrayList<Object> ResultadoTotal = new ArrayList<>();
        ArrayList<String> Productos = new ArrayList<>();
        ArrayList<Integer> Stock = new ArrayList<>();
        
        DAOInformes.conexion();
        ResultadoTotal = DAOInformes.ConsultarStock();
        
        
        Productos=(ArrayList<String>) ResultadoTotal.get(0);
        Stock=(ArrayList<Integer>) ResultadoTotal.get(1);
        
       int i;
       
        for (i=0;i<Productos.size();i++){
            
        jTable2.setValueAt(Productos.get(i), i ,0);
        jTable2.setValueAt(Stock.get(i), i ,1);
        
        }
        
        
        
        
        
        
    }//GEN-LAST:event_jButtonConsultarStockActionPerformed

    private void jButton1RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1RegresarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);  
    }//GEN-LAST:event_jButton1RegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIInformes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIInformes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIInformes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIInformes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIInformes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Consultar;
    private javax.swing.JButton jButton1Regresar;
    private javax.swing.JButton jButtonConsultarStock;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1FechaUno;
    private javax.swing.JTextField jTextField2FechaDos;
    // End of variables declaration//GEN-END:variables
}
