/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import persistencia.DaoInformes;


/**
 *
 * @author dcorr
 */
public class GUIInformes extends javax.swing.JFrame {

    /**
     * Creates new form GUIInformes
     */
    public GUIInformes() {
        initComponents();
    }
    
    public void guardaTabla(){
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jTextField1FechaUnoVentas = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2FechaDosVentas = new javax.swing.JTextField();
        jButton1ConsultarVentas = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1InformeVentas = new javax.swing.JTable();
        jButton1Regresar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1FechaUnoCostos = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField2FechaDosCostos = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1ConsultarCostos = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1InformeCostos = new javax.swing.JTable();
        jButton1ConsultarCompras = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1InformeCompras = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jTextField1FechaUnoCompras = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField2FechaDosCompras = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField1FechaUnoMasVendido = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField2FechaDosMasVendido = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jButton1ConsultarMasVendido = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableMasVendido = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/blue-wave-background-photoshop-backgrounds_opt.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1FechaUnoVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1FechaUnoVentasActionPerformed(evt);
            }
        });
        jTextField1FechaUnoVentas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1FechaUnoVentasKeyTyped(evt);
            }
        });
        getContentPane().add(jTextField1FechaUnoVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 80, -1));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel2.setText("a");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 96, 10, -1));

        jTextField2FechaDosVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2FechaDosVentasActionPerformed(evt);
            }
        });
        jTextField2FechaDosVentas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2FechaDosVentasKeyTyped(evt);
            }
        });
        getContentPane().add(jTextField2FechaDosVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 98, -1));

        jButton1ConsultarVentas.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jButton1ConsultarVentas.setText("Consultar");
        jButton1ConsultarVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ConsultarVentasActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1ConsultarVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, -1, -1));

        jTable1InformeVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Categoria", "Total Vendido"
            }
        ));
        jScrollPane1.setViewportView(jTable1InformeVentas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 330, 91));

        jButton1Regresar.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jButton1Regresar.setText("regresar");
        jButton1Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1RegresarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1Regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, -1, -1));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Fecha inicio");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 80, -1));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Fecha final");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 100, -1));

        jLabel5.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Consultar informe Ventas");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 330, 30));

        jLabel8.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Consultar informe Costos");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 320, 30));

        jTextField1FechaUnoCostos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1FechaUnoCostosKeyTyped(evt);
            }
        });
        getContentPane().add(jTextField1FechaUnoCostos, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, 80, -1));

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Fecha inicio");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, 80, -1));

        jTextField2FechaDosCostos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2FechaDosCostosKeyTyped(evt);
            }
        });
        getContentPane().add(jTextField2FechaDosCostos, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, 98, -1));

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel10.setText("a");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 90, 10, -1));

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Fecha final");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, 100, -1));

        jButton1ConsultarCostos.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jButton1ConsultarCostos.setText("Consultar");
        jButton1ConsultarCostos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ConsultarCostosActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1ConsultarCostos, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 80, -1, -1));

        jTable1InformeCostos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Categoria", "Costos"
            }
        ));
        jScrollPane3.setViewportView(jTable1InformeCostos);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, 330, 91));

        jButton1ConsultarCompras.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jButton1ConsultarCompras.setText("Consultar");
        jButton1ConsultarCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ConsultarComprasActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1ConsultarCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 300, -1, -1));

        jTable1InformeCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Total Compra"
            }
        ));
        jScrollPane4.setViewportView(jTable1InformeCompras);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, 330, 91));

        jLabel12.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Consultar informe Compras");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 320, 30));

        jTextField1FechaUnoCompras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1FechaUnoComprasKeyTyped(evt);
            }
        });
        getContentPane().add(jTextField1FechaUnoCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, 80, -1));

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Fecha inicio");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, 80, -1));

        jTextField2FechaDosCompras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2FechaDosComprasKeyTyped(evt);
            }
        });
        getContentPane().add(jTextField2FechaDosCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 310, 98, -1));

        jLabel14.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel14.setText("a");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 310, 10, -1));

        jLabel15.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Fecha final");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, 100, -1));

        jLabel16.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Consultar Productos mas vendidos");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 330, 30));

        jLabel17.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Fecha inicio");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 80, -1));

        jTextField1FechaUnoMasVendido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1FechaUnoMasVendidoKeyTyped(evt);
            }
        });
        getContentPane().add(jTextField1FechaUnoMasVendido, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 80, -1));

        jLabel18.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel18.setText("a");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 10, -1));

        jTextField2FechaDosMasVendido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2FechaDosMasVendidoActionPerformed(evt);
            }
        });
        jTextField2FechaDosMasVendido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2FechaDosMasVendidoKeyTyped(evt);
            }
        });
        getContentPane().add(jTextField2FechaDosMasVendido, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 98, -1));

        jLabel19.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Fecha final");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 100, -1));

        jButton1ConsultarMasVendido.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jButton1ConsultarMasVendido.setText("Consultar");
        jButton1ConsultarMasVendido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ConsultarMasVendidoActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1ConsultarMasVendido, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, -1, -1));

        jTableMasVendido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Cantidad Vendida"
            }
        ));
        jScrollPane5.setViewportView(jTableMasVendido);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 340, 91));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/blue-wave-background-photoshop-backgrounds_opt.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ConsultarVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ConsultarVentasActionPerformed
        // TODO add your handling code here:
        
        if (jTextField1FechaUnoVentas.getText().isEmpty() || jTextField2FechaDosVentas.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Los campos fecha deben estar llenos");
        }else{
        
        
        ArrayList<Object> Resultadoventas = new ArrayList<>();
        ArrayList<String> Categorias = new ArrayList<>();
        ArrayList<Integer> ventas = new ArrayList<>();
        
        DaoInformes.conexion();
        Resultadoventas=DaoInformes.consultainformecategorias(jTextField1FechaUnoVentas.getText(), jTextField2FechaDosVentas.getText());
        
      
        
        Categorias = (ArrayList<String>) Resultadoventas.get(0);
        ventas =(ArrayList<Integer>) (Resultadoventas.get(1));
        
        int i;
       
        for (i=0;i<Categorias.size();i++){
             DefaultTableModel modelo= (DefaultTableModel) jTable1InformeVentas.getModel();

            modelo.addRow(new Object[]{"",""});

            jTable1InformeVentas.setModel(modelo);   
            
            jTable1InformeVentas.setValueAt(Categorias.get(i), i ,0);
            jTable1InformeVentas.setValueAt(ventas.get(i), i ,1);
        }
        
         guardarTablaVentas(jTextField1FechaUnoVentas.getText(), jTextField2FechaDosVentas.getText());
        }
    }//GEN-LAST:event_jButton1ConsultarVentasActionPerformed

    private void jButton1RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1RegresarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);  
    }//GEN-LAST:event_jButton1RegresarActionPerformed

    private void jButton1ConsultarCostosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ConsultarCostosActionPerformed
        // TODO add your handling code here:
        
        if (jTextField1FechaUnoCostos.getText().isEmpty() || jTextField2FechaDosCostos.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Los campos fecha deben estar llenos");
        }
        else{
         ArrayList<Object> ResultadoCostos = new ArrayList<>();
        ArrayList<String> Categorias = new ArrayList<>();
        ArrayList<Integer> Costos = new ArrayList<>();
        
        DaoInformes.conexion();
        ResultadoCostos=DaoInformes.consultarInformeCostos(jTextField1FechaUnoCostos.getText(), jTextField2FechaDosCostos.getText());
        
      
        
        Categorias = (ArrayList<String>) ResultadoCostos.get(0);
        Costos =(ArrayList<Integer>) (ResultadoCostos.get(1));
        
        int i;
       
        for (i=0;i<Categorias.size();i++){
             DefaultTableModel modelo= (DefaultTableModel) jTable1InformeCostos.getModel();

            modelo.addRow(new Object[]{"",""});

            jTable1InformeCostos.setModel(modelo);   
            
            jTable1InformeCostos.setValueAt(Categorias.get(i), i ,0);
            jTable1InformeCostos.setValueAt(Costos.get(i), i ,1);
        }
        
         guardarTablaCostos(jTextField1FechaUnoCostos.getText(), jTextField2FechaDosCostos.getText());
         
        }
    }//GEN-LAST:event_jButton1ConsultarCostosActionPerformed

    private void jButton1ConsultarComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ConsultarComprasActionPerformed
        // TODO add your handling code here:
        
        if (jTextField1FechaUnoCompras.getText().isEmpty() || jTextField2FechaDosCompras.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Los campos fecha deben estar llenos");
        
        }else{
        ArrayList<Object> ResultadoCompra = new ArrayList<>();
        ArrayList<String> Categorias = new ArrayList<>();
        ArrayList<Integer> Compra = new ArrayList<>();
        
        DaoInformes.conexion();
        ResultadoCompra=DaoInformes.ConsultarInformeCompra(jTextField1FechaUnoCompras.getText(), jTextField2FechaDosCompras.getText());
        
      
        
        Categorias = (ArrayList<String>) ResultadoCompra.get(0);
        Compra =(ArrayList<Integer>) (ResultadoCompra.get(1));
        
        int i;
       
        for (i=0;i<Categorias.size();i++){
             DefaultTableModel modelo= (DefaultTableModel) jTable1InformeCompras.getModel();

            modelo.addRow(new Object[]{"",""});

            jTable1InformeCompras.setModel(modelo);   
            
            jTable1InformeCompras.setValueAt(Categorias.get(i), i ,0);
            jTable1InformeCompras.setValueAt(Compra.get(i), i ,1);
        }
        
          guardarTablaCompra(jTextField1FechaUnoCompras.getText(), jTextField2FechaDosCompras.getText());
        }
    }//GEN-LAST:event_jButton1ConsultarComprasActionPerformed

    private void jTextField2FechaDosVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2FechaDosVentasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2FechaDosVentasActionPerformed

    private void jTextField2FechaDosMasVendidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2FechaDosMasVendidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2FechaDosMasVendidoActionPerformed

    private void jButton1ConsultarMasVendidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ConsultarMasVendidoActionPerformed
        // TODO add your handling code here:
        
        if(jTextField1FechaUnoMasVendido.getText().isEmpty() || jTextField2FechaDosMasVendido.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Los campos fecha deben estar llenos");
        
        }else{
        ArrayList<Object> ResultadoMasVendidos = new ArrayList<>();
        ArrayList<String> Categorias = new ArrayList<>();
        ArrayList<Integer> MasVendidos = new ArrayList<>();
        
        DaoInformes.conexion();
        ResultadoMasVendidos=DaoInformes.ConsultarInformeMasVendidos(jTextField1FechaUnoMasVendido.getText(), jTextField2FechaDosMasVendido.getText());
        
      
        
        Categorias = (ArrayList<String>) ResultadoMasVendidos.get(0);
        MasVendidos =(ArrayList<Integer>) (ResultadoMasVendidos.get(1));
        
        int i;
       
        for (i=0;i<Categorias.size();i++){
             DefaultTableModel modelo= (DefaultTableModel) jTableMasVendido.getModel();

            modelo.addRow(new Object[]{"",""});

            jTableMasVendido.setModel(modelo);   
            
            jTableMasVendido.setValueAt(Categorias.get(i), i ,0);
            jTableMasVendido.setValueAt(MasVendidos.get(i), i ,1);
        }
        
        }
    }//GEN-LAST:event_jButton1ConsultarMasVendidoActionPerformed

    private void jTextField1FechaUnoVentasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1FechaUnoVentasKeyTyped
        // TODO add your handling code here:
         char caracter = evt.getKeyChar();

      // Verificar si la tecla pulsada  es un digito
     // Verificar si la tecla pulsada no es un digito
      if(Character.isDigit(caracter) || caracter=='/')
      {
          
      }else{
          getToolkit().beep();
          evt.consume();  // ignorar el evento de teclado
      }
    }//GEN-LAST:event_jTextField1FechaUnoVentasKeyTyped

    private void jTextField2FechaDosVentasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2FechaDosVentasKeyTyped
        // TODO add your handling code here:
         char caracter = evt.getKeyChar();

      // Verificar si la tecla pulsada  es un digito
     // Verificar si la tecla pulsada no es un digito
      if(Character.isDigit(caracter) || caracter=='/')
      {
          
      }else{
          getToolkit().beep();
          evt.consume();  // ignorar el evento de teclado
      }
    }//GEN-LAST:event_jTextField2FechaDosVentasKeyTyped

    private void jTextField1FechaUnoCostosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1FechaUnoCostosKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1FechaUnoCostosKeyTyped

    private void jTextField2FechaDosCostosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2FechaDosCostosKeyTyped
        // TODO add your handling code here:
         char caracter = evt.getKeyChar();

      // Verificar si la tecla pulsada  es un digito
     // Verificar si la tecla pulsada no es un digito
      if(Character.isDigit(caracter) || caracter=='/')
      {
          
      }else{
          getToolkit().beep();
          evt.consume();  // ignorar el evento de teclado
      }
    }//GEN-LAST:event_jTextField2FechaDosCostosKeyTyped

    private void jTextField1FechaUnoMasVendidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1FechaUnoMasVendidoKeyTyped
        // TODO add your handling code here:
         char caracter = evt.getKeyChar();

      // Verificar si la tecla pulsada  es un digito
     // Verificar si la tecla pulsada no es un digito
      if(Character.isDigit(caracter) || caracter=='/')
      {
          
      }else{
          getToolkit().beep();
          evt.consume();  // ignorar el evento de teclado
      }
    }//GEN-LAST:event_jTextField1FechaUnoMasVendidoKeyTyped

    private void jTextField2FechaDosMasVendidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2FechaDosMasVendidoKeyTyped
        // TODO add your handling code here:
         char caracter = evt.getKeyChar();

      // Verificar si la tecla pulsada  es un digito
     // Verificar si la tecla pulsada no es un digito
      if(Character.isDigit(caracter) || caracter=='/')
      {
          
      }else{
          getToolkit().beep();
          evt.consume();  // ignorar el evento de teclado
      }
    }//GEN-LAST:event_jTextField2FechaDosMasVendidoKeyTyped

    private void jTextField1FechaUnoComprasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1FechaUnoComprasKeyTyped
        // TODO add your handling code here:
         char caracter = evt.getKeyChar();

      // Verificar si la tecla pulsada  es un digito
     // Verificar si la tecla pulsada no es un digito
      if(Character.isDigit(caracter) || caracter=='/')
      {
          
      }else{
          getToolkit().beep();
          evt.consume();  // ignorar el evento de teclado
      }
    }//GEN-LAST:event_jTextField1FechaUnoComprasKeyTyped

    private void jTextField2FechaDosComprasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2FechaDosComprasKeyTyped
        // TODO add your handling code here:
         char caracter = evt.getKeyChar();

      // Verificar si la tecla pulsada  es un digito
     // Verificar si la tecla pulsada no es un digito
      if(Character.isDigit(caracter) || caracter=='/')
      {
          
      }else{
          getToolkit().beep();
          evt.consume();  // ignorar el evento de teclado
      }
    }//GEN-LAST:event_jTextField2FechaDosComprasKeyTyped

    private void jTextField1FechaUnoVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1FechaUnoVentasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1FechaUnoVentasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIInformes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIInformes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIInformes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIInformes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIInformes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1ConsultarCompras;
    private javax.swing.JButton jButton1ConsultarCostos;
    private javax.swing.JButton jButton1ConsultarMasVendido;
    private javax.swing.JButton jButton1ConsultarVentas;
    private javax.swing.JButton jButton1Regresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1InformeCompras;
    private javax.swing.JTable jTable1InformeCostos;
    private javax.swing.JTable jTable1InformeVentas;
    private javax.swing.JTable jTableMasVendido;
    private javax.swing.JTextField jTextField1FechaUnoCompras;
    private javax.swing.JTextField jTextField1FechaUnoCostos;
    private javax.swing.JTextField jTextField1FechaUnoMasVendido;
    private javax.swing.JTextField jTextField1FechaUnoVentas;
    private javax.swing.JTextField jTextField2FechaDosCompras;
    private javax.swing.JTextField jTextField2FechaDosCostos;
    private javax.swing.JTextField jTextField2FechaDosMasVendido;
    private javax.swing.JTextField jTextField2FechaDosVentas;
    // End of variables declaration//GEN-END:variables

    private void guardarTablaVentas(String fecha1, String fecha2) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            try {

            String sucursalesCSVFile = "src/Informe de ventas.txt";
            BufferedWriter bfw = new BufferedWriter(new FileWriter(sucursalesCSVFile ));
            bfw.write("Informe de ventas "+fecha1+" hasta "+fecha2+"");
            bfw.write("\n");
            bfw.write("\n");
            bfw.write("Categoria     |     ValorTotalVenta");
            bfw.write("\n");
            for (int i = 0 ; i < jTable1InformeVentas.getRowCount(); i++) //realiza un barrido por filas.
            {
                for(int j = 0 ; j < jTable1InformeVentas.getColumnCount();j++) //realiza un barrido por columnas.
                {
                    bfw.write(String.valueOf(jTable1InformeVentas.getValueAt(i,j)));
                    if (j < jTable1InformeVentas.getColumnCount() -1) { //agrega separador "," si no es el ultimo elemento de la fila.
                        bfw.write("     |     ");
                    }else{
                    bfw.write(".");
                    }
                }
                bfw.newLine(); //inserta nueva linea.
            }

            bfw.close(); //cierra archivo!
            System.out.println("El archivo fue salvado correctamente!");
        } catch (IOException e) {
            System.out.println("ERROR: Ocurrio un problema al salvar el archivo!" + e.getMessage());
        }
    }
    
    
    private void guardarTablaCostos(String fecha1, String fecha2) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            try {

            String sucursalesCSVFile = "src/Informe de costos.txt";
            BufferedWriter bfw = new BufferedWriter(new FileWriter(sucursalesCSVFile ));
            bfw.write("Informe de costos "+fecha1+" hasta "+fecha2+"");
            bfw.write("\n");
            bfw.write("\n");
            bfw.write("Categoria     |     Costos");
            bfw.write("\n");
            for (int i = 0 ; i < jTable1InformeCostos.getRowCount(); i++) //realiza un barrido por filas.
            {
                for(int j = 0 ; j < jTable1InformeCostos.getColumnCount();j++) //realiza un barrido por columnas.
                {
                    bfw.write(String.valueOf(jTable1InformeCostos.getValueAt(i,j)));
                    if (j < jTable1InformeCostos.getColumnCount() -1) { //agrega separador "," si no es el ultimo elemento de la fila.
                        bfw.write("     |     ");
                    }else{
                    bfw.write(".");
                    }
                }
                bfw.newLine(); //inserta nueva linea.
            }

            bfw.close(); //cierra archivo!
            System.out.println("El archivo fue salvado correctamente!");
        } catch (IOException e) {
            System.out.println("ERROR: Ocurrio un problema al salvar el archivo!" + e.getMessage());
        }
    }
    
    private void guardarTablaCompra(String fecha1, String fecha2) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            try {

            String sucursalesCSVFile = "src/Informe de compra.txt";
            BufferedWriter bfw = new BufferedWriter(new FileWriter(sucursalesCSVFile ));
            bfw.write("Informe de compra "+fecha1+" hasta "+fecha2+"");
            bfw.write("\n");
            bfw.write("\n");
            bfw.write("Nombre del producto     |     Total compra");
            bfw.write("\n");
            for (int i = 0 ; i < jTable1InformeCompras.getRowCount(); i++) //realiza un barrido por filas.
            {
                for(int j = 0 ; j < jTable1InformeCompras.getColumnCount();j++) //realiza un barrido por columnas.
                {
                    bfw.write(String.valueOf(jTable1InformeCompras.getValueAt(i,j)));
                    if (j < jTable1InformeCompras.getColumnCount() -1) { //agrega separador "," si no es el ultimo elemento de la fila.
                        bfw.write("          |          ");
                    }else{
                    bfw.write(".");
                    }
                }
                bfw.newLine(); //inserta nueva linea.
            }

            bfw.close(); //cierra archivo!
            System.out.println("El archivo fue salvado correctamente!");
        } catch (IOException e) {
            System.out.println("ERROR: Ocurrio un problema al salvar el archivo!" + e.getMessage());
        }
    }
}
