/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import persistencia.DAOProducto;

/**
 *
 * @author dcorr
 */
public class GUIProductosVencimiento extends javax.swing.JFrame {

    /**
     * Creates new form ProductosVencimiento
     */
    public GUIProductosVencimiento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1Regresar = new javax.swing.JButton();
        jButton1Consultar = new javax.swing.JButton();
        jTextField1FechaAviso = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(610, 300));
        setResizable(false);
        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Fecha vencimiento", "Fecha aviso"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(170, 50, 429, 170);

        jButton1Regresar.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jButton1Regresar.setText("Regresar");
        jButton1Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1RegresarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1Regresar);
        jButton1Regresar.setBounds(20, 220, 120, 29);

        jButton1Consultar.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jButton1Consultar.setText("Consultar");
        jButton1Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1Consultar);
        jButton1Consultar.setBounds(10, 110, 130, 29);
        getContentPane().add(jTextField1FechaAviso);
        jTextField1FechaAviso.setBounds(10, 144, 130, 20);

        jLabel2.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Consultar fecha de vencimiento");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(4, 4, 590, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/blue-wave-background-photoshop-backgrounds_opt.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-20, -10, 650, 290);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ConsultarActionPerformed
        // TODO add your handling code here:
        
        ArrayList<ArrayList> ProductosVencerse = new ArrayList<>();
        ArrayList<String> ProductosVencerse2 = new ArrayList<>();
        
        DAOProducto.conexion();
        ProductosVencerse= DAOProducto.consultarProductosVencimiento(jTextField1FechaAviso.getText());
        
         
        
         
         ProductosVencerse2=ProductosVencerse.get(0);
         
         
         System.out.println(ProductosVencerse2);
         
        int i;
       
        for (i=0;i<ProductosVencerse.size();i++){
            
          
           DefaultTableModel modelo= (DefaultTableModel) jTable1.getModel();
           
           modelo.addRow(new Object[]{"","",""});
           
           jTable1.setModel(modelo);
           
           jTable1.setValueAt(ProductosVencerse2.get(0), i ,0);
           jTable1.setValueAt(ProductosVencerse2.get(1), i ,1);
           jTable1.setValueAt(ProductosVencerse2.get(2), i ,2);
           
           ProductosVencerse2.remove(0);
           ProductosVencerse2.remove(0);
           ProductosVencerse2.remove(0);
        }
        
    }//GEN-LAST:event_jButton1ConsultarActionPerformed

    private void jButton1RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1RegresarActionPerformed
        // TODO add your handling code here:
          this.setVisible(false);
    }//GEN-LAST:event_jButton1RegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIProductosVencimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIProductosVencimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIProductosVencimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIProductosVencimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIProductosVencimiento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Consultar;
    private javax.swing.JButton jButton1Regresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1FechaAviso;
    // End of variables declaration//GEN-END:variables


}
