/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import modelo.Producto;
import persistencia.DAOProducto;

/**
 *
 * @author dcorr
 */
public class GUIProductos extends javax.swing.JFrame {

    /**
     * Creates new form GUIProductos
     */
    
 
    public GUIProductos() {
        initComponents();
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonRegresar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableTablaProductos = new javax.swing.JTable();
        jLabelCodigoProducto = new javax.swing.JLabel();
        jLabelNombreProducto = new javax.swing.JLabel();
        jTextFieldNombreProducto = new javax.swing.JTextField();
        jTextFieldCodigoProducto = new javax.swing.JTextField();
        jLabelPrecioVenta = new javax.swing.JLabel();
        jTextFieldPrecioVenta = new javax.swing.JTextField();
        jButtonRegistrarProducto = new javax.swing.JButton();
        jLabelCategoria = new javax.swing.JLabel();
        jComboBoxCategoria = new javax.swing.JComboBox<>();
        jButtonAgregarProducto = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1Cpp = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonRegresar.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jButtonRegresar.setText("Regresar");
        jButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 427, -1, -1));

        jTableTablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CodigoProducto", "Nombre", "Precio Venta", "Categoria", "cpp"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableTablaProductos);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 282, 700, 139));

        jLabelCodigoProducto.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabelCodigoProducto.setText("Codigo Producto");
        getContentPane().add(jLabelCodigoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 58, -1, -1));

        jLabelNombreProducto.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabelNombreProducto.setText("Nombre Producto");
        getContentPane().add(jLabelNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jTextFieldNombreProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreProductoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 210, -1));
        getContentPane().add(jTextFieldCodigoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 210, -1));

        jLabelPrecioVenta.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabelPrecioVenta.setText("Precio de Venta");
        getContentPane().add(jLabelPrecioVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));
        getContentPane().add(jTextFieldPrecioVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 210, -1));

        jButtonRegistrarProducto.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jButtonRegistrarProducto.setText("Registrar Producto");
        jButtonRegistrarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarProductoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegistrarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, -1, -1));

        jLabelCategoria.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabelCategoria.setText("Categoria");
        getContentPane().add(jLabelCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jComboBoxCategoria.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jComboBoxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aseo Personal", "Aseo Hogar ", "Bebidas", "Bisuteria", "Jugueteria", "Ferreteria", "Snacks", "Mascotas", "Medicamentos", "Papeleria" }));
        jComboBoxCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCategoriaActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 98, 20));

        jButtonAgregarProducto.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jButtonAgregarProducto.setText("Agregar Producto");
        jButtonAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarProductoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAgregarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/680-6808809_plan-web-tienda-virtual-productos-dibujos-hd-png_opt.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 300, 210));

        jLabel3.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("registro de productos");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 320, 40));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel4.setText("Cpp");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 60, -1));

        jTextField1Cpp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1CppActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1Cpp, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 210, -1));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel5.setText("Cantidad");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 90, -1));

        jTextField1.setEditable(false);
        jTextField1.setText("0");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 210, -1));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/blue-wave-background-photoshop-backgrounds_opt.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 460));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegistrarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarProductoActionPerformed
        // TODO add your handling code here:
        JTable jTableTablaProductos1 = jTableTablaProductos;
       
        
        
        int filas=jTableTablaProductos1.getRowCount();
        int i;
        
        
        
        for (i =0 ; i<filas;i++){
            
            Producto nuevoProducto= new Producto();
            
            nuevoProducto.setId((int) jTableTablaProductos1.getValueAt(i, 0));
            nuevoProducto.setNombre((String) jTableTablaProductos1.getValueAt(i, 1));
            nuevoProducto.setCategoria((String) jTableTablaProductos1.getValueAt(i, 3));
            nuevoProducto.setPrecioVenta((double) jTableTablaProductos1.getValueAt(i, 2));
            nuevoProducto.setCantidad(0);
            nuevoProducto.setCpp((double) jTableTablaProductos1.getValueAt(i, 4));
            
            DAOProducto.conexion();
            DAOProducto.GuardarProducto(nuevoProducto);
            
        
        }
        
        
        
        
        
    }//GEN-LAST:event_jButtonRegistrarProductoActionPerformed

    private void jButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarActionPerformed
        // TODO add your handling code here:
        
        this.setVisible(false);
        
        
    }//GEN-LAST:event_jButtonRegresarActionPerformed

    private void jComboBoxCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCategoriaActionPerformed

    private void jButtonAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarProductoActionPerformed
        // TODO add your handling code here:

        DefaultTableModel modelo=(DefaultTableModel) jTableTablaProductos.getModel();

        Object [] fila=new Object[5];

        fila[0]=Integer.parseInt(jTextFieldCodigoProducto.getText());

        fila[1]=jTextFieldNombreProducto.getText();

        fila[2]=Double.parseDouble(jTextFieldPrecioVenta.getText());

        fila[3]=jComboBoxCategoria.getSelectedItem();
        
        fila[4]= Double.parseDouble(jTextField1Cpp.getText());

        modelo.addRow(fila);

        jTableTablaProductos.setModel(modelo);

    }//GEN-LAST:event_jButtonAgregarProductoActionPerformed

    private void jTextFieldNombreProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreProductoActionPerformed

    private void jTextField1CppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1CppActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1CppActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIProductos().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregarProducto;
    private javax.swing.JButton jButtonRegistrarProducto;
    private javax.swing.JButton jButtonRegresar;
    private javax.swing.JComboBox<String> jComboBoxCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelCategoria;
    private javax.swing.JLabel jLabelCodigoProducto;
    private javax.swing.JLabel jLabelNombreProducto;
    private javax.swing.JLabel jLabelPrecioVenta;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableTablaProductos;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField1Cpp;
    private javax.swing.JTextField jTextFieldCodigoProducto;
    private javax.swing.JTextField jTextFieldNombreProducto;
    private javax.swing.JTextField jTextFieldPrecioVenta;
    // End of variables declaration//GEN-END:variables

   
}
